config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    post '/trigger/:trigger_name',  to: 'house#trigger'
    put '/trigger/toggle',          to: 'house#toggle'
    put '/bender/lamps',            to: 'lamps#update'
    put '/bender/lamps/:id',        to: 'lamps#set_color'
    put '/bender/sensor_light',     to: 'lamps#sensor_light'
    put '/bender/:id/socket',       to: 'socket#update'
  end

  resources :activities
  resources :devices do
    resources :device_configurations
  end

  resources :triggers
  root 'home#index'
end

app/models/device.rb
class Device < ActiveRecord::Base
  has_many :device_configurations

  validates :name, :device_type, presence: true
  IN = 'in'
  OUT = 'out'
  TYPES = [Device::IN, Device::OUT]
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_action :set_device, only: [:show, :edit, :update, :destroy]

  def index
    @devices = Device.all
  end

  def show
  end

  def new
    @device = Device.new
  end

  def edit
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      redirect_to @device, notice: 'Device was successfully created.'
    else
      render :new
    end
  end

  def update
    if @device.update(device_params)
      redirect_to @device, notice: 'Device was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @device.destroy
    redirect_to devices_url, notice: 'Device was successfully destroyed.'
  end

  private

  def set_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :description, :device_type, :module_name)
  end
end

app/views/devices/_form.html.erb
  <div class="col-lg-12">
    <div class="form-panel">
      <h4 class="mb"><i class="fa fa-angle-right"></i> Device </h4>

      <%= form_for @device, html: { class: 'form-horizontal style-form' } do |f| %>
        <div class="form-group">
          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :name %></label>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :description %></label>
          <div class="col-sm-10">
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :device_type %></label>
          <div class="col-sm-3">
            <div class="switch switch-square" data-on-label="<i class='fa'>In</i>" data-off-label="<i class='fa'>Out</i>">
              <%= f.check_box :device_type, {}, Device::IN, Device::OUT %>
            </div>
          </div>

          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :module_name %></label>
          <div class="col-sm-2">
            <%= f.text_field :module_name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10">
            <%= f.submit class: 'btn btn-theme02' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/devices/edit.html.erb
<div class="row mt">
  <%= render 'form' %>
</div>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Lista de Devices</h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list ui-sortable">
            <%= render partial: 'devices/shared/index_items', collection: @devices, as: :device %>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'New Device', new_device_path, class: 'btn btn-success btn-sm pull-left' %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form' %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Device </h5></div>
        <div class="pull-right">
          <%= link_to device_device_configurations_path(@device), class: 'btn btn-theme02 btn-xs' do %>
            <i class=" fa fa-cog fa-spin"></i> Configurações
          <% end %>
        </div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list">
            <li>
              <div class="task-title">
                <b>Name: </b>
                <span class="task-title-sp"><%= @device.name %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Description: </b>
                <span class="task-title-sp"><%= @device.description %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Type: </b>
                <span class="task-title-sp"><%= @device.device_type %></span>
                <label><span class="fa <%= device_type_icon @device.device_type %>"></span></label>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Module: </b>
                <span class="task-title-sp"><%= @device.module_name %></span>
              </div>
            </li>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'Edit', edit_device_path(@device), class: 'btn btn-success btn-sm pull-left' %>
          <%= link_to 'Back', devices_path, class: 'btn btn-default btn-sm pull-right' %>
        </div>
      </div>
    </section>
  </div>
</div>