config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    post '/trigger/:trigger_name',  to: 'house#trigger'
    put '/trigger/toggle',          to: 'house#toggle'
    put '/bender/lamps',            to: 'lamps#update'
    put '/bender/lamps/:id',        to: 'lamps#set_color'
    put '/bender/sensor_light',     to: 'lamps#sensor_light'
    put '/bender/:id/socket',       to: 'socket#update'
  end

  resources :activities
  resources :devices do
    resources :device_configurations
  end

  resources :triggers
  root 'home#index'
end

app/models/device_configuration.rb
class DeviceConfiguration < ActiveRecord::Base
  belongs_to :device
  validates :name, :content, presence: true
end

app/controllers/device_configurations_controller.rb
class DeviceConfigurationsController < ApplicationController
  before_action :set_device_configuration, only: [:show, :edit, :update, :destroy]
  before_action :set_device

  def index
    @device_configurations = @device.device_configurations
  end

  def show
  end

  def new
    @device_configuration = DeviceConfiguration.new
  end

  def edit
  end

  def create
    hash = device_configuration_params.merge(device_id: @device.id)
    @device_configuration = DeviceConfiguration.new(hash)

    if @device_configuration.save
      path = device_device_configurations_path(@device, @device_configuration)
      redirect_to path, notice: 'Device configuration was successfully created.'
    else
      render :new
    end
  end

  def update
    if @device_configuration.update(device_configuration_params)
      path = device_device_configuration_path(@device, @device_configuration)
      redirect_to path, notice: 'Device configuration was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @device_configuration.destroy
    path = device_device_configurations_url(@device_configuration.device)
    redirect_to path, notice: 'Device configuration was successfully destroyed.'
  end

  private

  def set_device_configuration
    @device_configuration = DeviceConfiguration.find(params[:id])
  end

  def device_configuration_params
    params.require(:device_configuration).permit(:name, :description, :content)
  end

  def set_device
    @device = Device.find(params[:device_id])
  end
end

app/views/device_configurations/_form.html.erb
<div class="col-md-12">
  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Configuração do Dispositivo</h4>

    <%= form_for [@device, @device_configuration], html: { class: 'form-horizontal style-form' } do |f| %>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label"><%= f.label :name %></label>
        <div class="col-sm-10">
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label"><%= f.label :description %></label>
        <div class="col-sm-10">
          <%= f.text_area :description, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label"><%= f.label :content %></label>
        <div class="col-sm-10">
          <%= f.text_area :content, class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: 'btn btn-theme02' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/device_configurations/edit.html.erb
<div class="row mt">
  <%= render 'device_configurations/shared/breadcrumb' %>
  <%= render 'form' %>
</div>

<%= link_to 'Show', device_device_configuration_path(@device, @device_configuration) %> |
<%= link_to 'Back', device_device_configurations_path(@device_configuration.device) %>

app/views/device_configurations/index.html.erb
<div class="row mt">
  <%= render 'device_configurations/shared/breadcrumb' %>

  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Lista de Configurações</h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list ui-sortable">
            <%= render partial: 'device_configurations/shared/index_items', collection: @device_configurations, as: :config %>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'New configuration', new_device_device_configuration_path(@device), class: 'btn btn-success btn-sm pull-left' %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/device_configurations/new.html.erb
<div class="row mt">
  <%= render 'device_configurations/shared/breadcrumb' %>
  <%= render 'form' %>
</div>
<%= link_to 'Back', device_device_configurations_path(@device) %>

app/views/device_configurations/show.html.erb
<div class="row mt">
  <%= render 'device_configurations/shared/breadcrumb' %>
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Configuração do Dispositivo</h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list">
            <li>
              <div class="task-title">
                <b>Name: </b>
                <span class="task-title-sp"><%= @device_configuration.name %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Description: </b>
                <span class="task-title-sp"><%= @device_configuration.description %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Content: </b>
                <span class="task-title-sp"><%= @device_configuration.content %></span>
              </div>
            </li>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'Edit', edit_device_device_configuration_path(@device, @device_configuration), class: 'btn btn-success btn-sm pull-left' %>
          <%= link_to 'Back', device_device_configurations_path(@device, @device_configuration), class: 'btn btn-default btn-sm pull-right' %>
        </div>
      </div>
    </section>
  </div>
</div>