config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    post '/trigger/:trigger_name',  to: 'house#trigger'
    put '/trigger/toggle',          to: 'house#toggle'
    put '/bender/lamps',            to: 'lamps#update'
    put '/bender/lamps/:id',        to: 'lamps#set_color'
    put '/bender/sensor_light',     to: 'lamps#sensor_light'
    put '/bender/:id/socket',       to: 'socket#update'
  end

  resources :activities
  resources :devices do
    resources :device_configurations
  end

  resources :triggers
  root 'home#index'
end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :trigger
  belongs_to :device_configuration
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render :show, status: :created, location: @activity }
      else
        format.html { render :new }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render :show, status: :ok, location: @activity }
      else
        format.html { render :edit }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url, notice: 'Activity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_activity
    @activity = Activity.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def activity_params
    params.require(:activity).permit(:trigger_id, :device_configuration_id)
  end
end

app/views/activities/_form.html.erb
<div class="col-md-12">
  <div class="form-panel">
    <h4 class="mb"><i class="fa fa-angle-right"></i> Configuração do Dispositivo</h4>

    <%= form_for @activity, html: { class: 'form-horizontal style-form' } do |f| %>
      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label"><%= f.label :trigger_id %></label>
        <div class="col-sm-10">
          <%= f.collection_select(:trigger_id, triggers_for_select, :id, :name, {prompt: true}, { class: 'form-control' })%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-2 col-sm-2 control-label"><%= f.label :device_configuration_id  %></label>
        <div class="col-sm-10">
          <%= f.collection_select(:device_configuration_id, configurations_for_select, :id, :name, {prompt: true}, { class: 'form-control' })%>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10">
          <%= f.submit class: 'btn btn-theme02' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/activities/edit.html.erb
<div class="row mt">
  <%= render 'form' %>
</div>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Atividades</h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list ui-sortable">
            <%= render partial: 'activities/shared/index_items', collection: @activities, as: :activity %>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'Nova Atividade', new_activity_path, class: 'btn btn-success btn-sm pull-left' %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/activities/new.html.erb
<div class="row mt">
  <%= render 'form' %>
</div>
<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i>Atividade</h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list">
            <li>
              <div class="task-title">
                <b>Trigger: </b>
                <span class="task-title-sp"><%= @activity.trigger.name %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Configuração: </b>
                <span class="task-title-sp"><%= @activity.device_configuration.name %></span>
              </div>
            </li>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'Edit', edit_activity_path(@activity), class: 'btn btn-success btn-sm pull-left' %>
          <%= link_to 'Back', activities_path, class: 'btn btn-default btn-sm pull-right' %>
        </div>
      </div>
    </section>
  </div>
</div>