config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    post '/trigger/:trigger_name',  to: 'house#trigger'
    put '/trigger/toggle',          to: 'house#toggle'
    put '/bender/lamps',            to: 'lamps#update'
    put '/bender/lamps/:id',        to: 'lamps#set_color'
    put '/bender/sensor_light',     to: 'lamps#sensor_light'
    put '/bender/:id/socket',       to: 'socket#update'
  end

  resources :activities
  resources :devices do
    resources :device_configurations
  end

  resources :triggers
  root 'home#index'
end

app/models/trigger.rb
class Trigger < ActiveRecord::Base
  validates :name, presence: true

  def self.execute(trigger_name)
    activities = search_activities trigger_name

    activities.each do |activity|
      exec = Home::Executor.build(activity)
      exec.execute
    end
  end

  def self.search_activities(trigger_name)
    params = { 'triggers.name' => trigger_name }
    Activity.joins(:trigger).where(params)
  end
end

app/controllers/triggers_controller.rb
class TriggersController < ApplicationController
  before_action :set_trigger, only: [:show, :edit, :update, :destroy]

  def index
    @triggers = Trigger.all
  end

  def show
  end

  def new
    @trigger = Trigger.new
  end

  def edit
  end

  def create
    @trigger = Trigger.new(trigger_params)

    if @trigger.save
      redirect_to @trigger, notice: 'Trigger was successfully created.'
    else
      render :new
    end
  end

  def update
    if @trigger.update(trigger_params)
      redirect_to @trigger, notice: 'Trigger was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @trigger.destroy
    redirect_to triggers_url, notice: 'Trigger was successfully destroyed.'
  end

  private

  def set_trigger
    @trigger = Trigger.find(params[:id])
  end

  def trigger_params
    params.require(:trigger).permit(:name, :description)
  end
end

app/views/triggers/_form.html.erb
<div class="row mt">
  <div class="col-lg-12">
    <div class="form-panel">
      <h4 class="mb"><i class="fa fa-angle-right"></i> Trigger </h4>
      <%= form_for @trigger, html: { class: 'form-horizontal style-form' } do |f| %>

        <div class="form-group">
          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :name %></label>
          <div class="col-sm-10">
            <%= f.text_field :name, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <label class="col-sm-2 col-sm-2 control-label"><%= f.label :description %></label>
          <div class="col-sm-10">
            <%= f.text_area :description, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-10">
            <%= f.submit class: 'btn btn-theme02' %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/triggers/edit.html.erb
<h3><i class="fa fa-angle-right"></i> Edit </h3>

<%= render 'form' %>

<%= link_to 'Show', @trigger %> |
<%= link_to 'Back', triggers_path %>

app/views/triggers/index.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Lista de Triggers </h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list ui-sortable">
            <%= render partial: 'triggers/shared/index_items', collection: @triggers, as: :trigger %>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'New Trigger', new_trigger_path, class: 'btn btn-success btn-sm pull-left' %>
        </div>
      </div>
    </section>
  </div>
</div>

app/views/triggers/new.html.erb
<h1>New Trigger</h1>

<%= render 'form' %>

<%= link_to 'Back', triggers_path %>

app/views/triggers/show.html.erb
<div class="row mt">
  <div class="col-md-12">
    <section class="task-panel tasks-widget">
      <div class="panel-heading">
        <div class="pull-left"><h5><i class="fa fa-tasks"></i> Trigger </h5></div>
        <br>
      </div>
      <div class="panel-body">
        <div class="task-content">
          <ul class="task-list">
            <li>
              <div class="task-title">
                <b>Name: </b>
                <span class="task-title-sp"><%= @trigger.name %></span>
              </div>
            </li>
            <li>
              <div class="task-title">
                <b>Description: </b>
                <span class="task-title-sp"><%= @trigger.description %></span>
              </div>
            </li>
          </ul>
        </div>

        <div class=" add-task-row">
          <%= link_to 'Edit', edit_trigger_path(@trigger), class: 'btn btn-success btn-sm pull-left' %>
          <%= link_to 'Back', triggers_path, class: 'btn btn-default btn-sm pull-right' %>
        </div>
      </div>
    </section>
  </div>
</div>